### ISSUE TITLE
Add field 'feedback url'

### ISSUE THREAD

**Issue by saerdnaer** [voc/schedule#39]
-> New field on Event in schedue.xml and schedule.json with absolute URL to the corresponding form as specified in https://git.cccv.de/hub/hub/-/issues/430#note_20618

* [x] added field to json + xml schema in 
* https://github.com/EventFahrplan/EventFahrplan/issues/114
* [hub/hub#430](https://git.cccv.de/hub/hub/-/issues/430)

**Comment by johnjohndoe** [comment]
I like to continue the discussion on how to integrate a `feedback_url` in the **aggregated** schedule XML containing data from various backend (_frab_, _Pretalx_, wiki, ...). Here I try to propose a "specification" - please be welcome to correct me, to complement or to comment.

# Current potential consensus
- Each backend agrees to add a `feedback_url` node as a **top level node** in the XML. See https://github.com/frab/frab/issues/550.
- The `feedback_url` must be a **fully qualified URL** because the feedback form might be hosted on a different domain/server.
- The `feedback_url` (template) contains an **event identifier parameter/placeholder**.

# Aggregated schedule
- Each `event` node must contain a `feedback_url` **child node** because the events in a room might be aggregated from different backends.
- The aggregation script **replaces the URL parameter** for the specific event.
- A client application can use the URL as is.

---

/cc @manno @rixx @toto

**Comment by rixx** [comment]
I'm not sure that adding a mandatory field to the already-tentative "standard" of schedule.xml is a good idea, because it would mean that a number of older/different tools won't pass validation.

Other than that: pretalx will accept PRs implementing whatever the final consensus turns out to be, I don't care which particular proposal wins out.

**Comment by saerdnaer** [comment]
@rixx Of course this would be an optional field, so old exports would still be valid.

**Comment by saerdnaer** [comment]
@johnjohndoe For aggregated schedules I am currently thinking about a redirect service e.g. https://data.c3voc.de/feedback/36C3/6a32cb72-a69d-423c-91b5-60d88eb8e6c7 or https://data.c3voc.de/feedback/6a32cb72-a69d-423c-91b5-60d88eb8e6c7 which then would redirect to the corresponding form. In this case this would be announced via `"feedback_url": "https://data.c3voc.de/feedback/{guid}",` or `<feedback_url>https://data.c3voc.de/feedback/{guid}</feedback_url>` in the schedule header.

**Comment by johnjohndoe** [comment]
@saerdnaer At this point a redirect service looks fine to me. I guess Android should be able to handle this.

:thinking: In the future I might want to implement a **native feedback form** which allows users to **stay** in the app when submitting a feedback. This would require in app knowledge about the **kind** of feedback form. I here assume that the feedback forms of frab and Pretalx **differ** by their fields. This native feedback form could be implemented as an API request if an endpoint available.

**Comment by toto** [comment]
@johnjohndoe Indeed having user feedback native in app would be great. 

I see three options to make this happen: 

1. A unified endpoint that could talk to both systems somewhere (since the iOS apps use a middleware anyways it could be used for this)
2. We could try to get pretax and frab to unify the fields
3. We could specify the fields and values in some way in the format. 

I think the 3rd option is probably to complex for it's own good and it requires a lot of code on all platforms

**Comment by rixx** [comment]
I'm afraid pretalx won't be able to commit to complete compatibility with frab feedback forms. Providing compatibile exports is something I'll gladly provide, but limiting pretalx functionality would be going too far, especially as the feedback form will probably evolve over time.

**Comment by johnjohndoe** [comment]
To keep the scope small and reachable I like to limit myself to the conversion about the `feedback_url`. I agree with what was written - especially with the new field being optional. Is there anything stopping us at this point to continue with this iteration step?

@toto We can discuss a potential native feedback form somewhere else if you like.

**Comment by toto** [comment]
Sounds good to me 👍

**Comment by johnjohndoe** [comment]
:link: [Frab/Pretalx-Feedback URL in aggregiertem schedule.xml/json
](https://git.cccv.de/hub/hub/-/issues/430)

**Comment by johnjohndoe** [comment]
@rixx & @toto Would you please join the discussion in the new issue linked above :arrow_up: to bring the topic forward?
