### ISSUE TITLE
merged version numbers

### ISSUE THREAD

**Issue by saerdnaer** [voc/schedule#5]

**Comment by saerdnaer** [comment]
Was implemented for json schedule in https://github.com/voc/schedule/commit/01a10e21e4e435dd47df0cbba45f21deee9b5f34#diff-9949c26e4143c91907d68ee62619fa15R150

Still open issue: How to merge version numbers...

**Comment by a-tze** [comment]
Version Number 1 + "-" + Version Number 2

should at least be stable /wrt to sorting. prerequisite is that input schedules (version numbers) are always processed in same order.

**Comment by saerdnaer** [comment]
Currently there is no guarantee that the version number changes with every small little change. We also have some unversioned content as input like the self-organized session from wiki at events.ccc.de. I personally would prefer some hash over the content or an last change date...

**Comment by a-tze** [comment]
proposal: 
  - hash (-part) over content replaces version numer in schedules w/o version number in them, otherwise take version number from input
  - concatenation of those values results in output version number

I think this is the most transparent. Hashing inputs that have a version number are harder to track. If the resulting version is something like '0.9-ad8e39' a human can derive at least a little bit of information.

**Comment by saerdnaer** [comment]
so for the 32C3 use case, this would be 0.9-ad8e39_0.3-fefeba_abcde? (cccv frab + sendezentrum + wiki)

**Comment by a-tze** [comment]
since SZ has a version number, it should be more like '0.9-0.3-fefeba_abcde'. The idea is that sorting works, but of course it doesn't work for the hashed parts.

**Comment by saerdnaer** [comment]
was implemented this year
